import { useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, MessageCircle, Mic, Sparkles, Target } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api,json,ApiError } from './api';
import { dateTime, ErrorMessage,PageHeading,useResource } from './ui';
import { download } from './career-profile';
type Topic={topic:string;why:string;outcome:string;priority:string};
type Plan={id:string;drive_id?:string;role_title:string;company_name:string;target_date:string;context_status?:{main_resume_changed:boolean;main_resume_submission_id?:string};plan:{summary:string;goal:string;deadline_notice?:string;uncovered_topics?:string[];source_context?:{deadline_at?:string;deadline_basis?:string};priority_topics:Topic[];daily_roadmap:{day:number;session_id?:string;session_type?:string;planned_at?:string;schedule_status?:string;duration_minutes?:number;title:string;focus:string;skill?:string;activities:string[];success_check:string}[];discussion_starters:string[]};messages?:{id:string;role:string;content:string}[]};
type CoachCycle={id:string;plan_id:string;drive_id?:string;source_evaluation_id?:string;focus_skills:{focus?:string;problem?:string;actions?:string[]}[];call_scheduled_for:string;call_duration_minutes:number;call_started_at?:string;call_completed_at?:string;practice_status:string;interview_scheduled_for?:string;interview_duration_minutes?:number;interview_difficulty?:string;practice_url?:string};
type CoachRecommendation={available:boolean;evaluation_id?:string;drive_id?:string;plan_id?:string;role_title?:string;message:string;weak_skills:{focus?:string;problem?:string;actions?:string[]}[];cycle?:CoachCycle};
type CoachOverview={upcoming_drives:{drive_id:string;company_name:string;role_title:string;job_description?:string;window_start_at?:string;window_end_at?:string;has_coaching_plan:boolean;next_action?:string}[];completed_placements?:{drive_id:string;company_name:string;role_title:string;completed_at?:string;feedback_status:string;has_coaching_plan:boolean}[];plans:Plan[];main_resume?:{submission_id:string;label:string;uploaded_at?:string}|null;completed_drive_recommendation?:CoachRecommendation};
type CoachReadiness={score:number;skills:{skill:string;state:string;source?:string}[];explanation:{skill:string;state:string;importance:number}[]};
type CoachDiagnostic={id:string;status:string;tasks_json:{task_id:string;sub_skill:string;format:string;question:string}[];answers_json:Record<string,string>;result_json?:{skills:{skill:string;state:string;assessed_tasks:number;demonstrated_tasks:number}[]}};
const COACH_AI_TIMEOUT_MS=180_000;
function indiaDateInput(value?:string){if(!value)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value));const fields=Object.fromEntries(parts.map(part=>[part.type,part.value]));return `${fields.year}-${fields.month}-${fields.day}`}
export function Coach(){
 const overview=useResource<CoachOverview>('/api/student/coach/overview'),recommendation=useResource<CoachRecommendation>('/api/student/coach/latest-recommendation'),cycles=useResource<{cycles:CoachCycle[]}>('/api/student/coach/training-cycles'),readiness=useResource<CoachReadiness>('/api/student/coach/readiness'),[params]=useSearchParams(),navigate=useNavigate();
 const requestedDrive=params.get('drive')||''; const requestedPlan=params.get('plan')||''; const requestedSession=params.get('session')||'';
 const [selected,setSelected]=useState(''),[role,setRole]=useState(''),[company,setCompany]=useState(''),[jd,setJd]=useState(''),[date,setDate]=useState(''),[drive,setDrive]=useState(''),[diagnosticReady,setDiagnosticReady]=useState(false),[busy,setBusy]=useState(false),[accepting,setAccepting]=useState(false),[error,setError]=useState('');
 function chooseDrive(id:string){if(id===drive)return;setDiagnosticReady(false);if(!id){setDrive('');setError('');return}const upcoming=overview.data?.upcoming_drives.find(item=>item.drive_id===id);const completed=overview.data?.completed_placements?.find(item=>item.drive_id===id);const opportunity=upcoming||completed;if(!opportunity){setDrive('');setError('This placement opportunity is no longer available for preparation. Choose an available opportunity.');return}setDrive(id);setError('');setRole(opportunity.role_title);setJd((upcoming?.job_description||'').slice(0,20000));setCompany(opportunity.company_name||'');const target=completed?indiaDateInput(new Date(Date.now()+7*86400000).toISOString()):indiaDateInput(upcoming?.window_start_at);setDate(target>=indiaDateInput(new Date().toISOString())?target:'');const existing=overview.data?.plans?.find(p=>p.drive_id===id);if(existing)setSelected(existing.id)}
 useEffect(()=>{if(!overview.data?.upcoming_drives||drive||requestedPlan)return;const accessible=[...overview.data.upcoming_drives,...(overview.data.completed_placements||[])];const next=(requestedDrive&&accessible.some(item=>item.drive_id===requestedDrive)?requestedDrive:'')||overview.data.upcoming_drives[0]?.drive_id;if(next)void chooseDrive(next)},[requestedDrive,requestedPlan,overview.data?.upcoming_drives,overview.data?.completed_placements]);
 useEffect(()=>{const recommendedPlan=recommendation.data?.plan_id;if(recommendedPlan&&overview.data?.plans?.some(plan=>plan.id===recommendedPlan))setSelected(recommendedPlan)},[recommendation.data?.plan_id,overview.data?.plans]);
 useEffect(()=>{if(requestedPlan&&overview.data?.plans?.some(plan=>plan.id===requestedPlan)){setSelected(requestedPlan);setDrive(overview.data.plans.find(plan=>plan.id===requestedPlan)?.drive_id||'')}},[overview.data?.plans,requestedPlan]);
 const isCompleted=Boolean(overview.data?.completed_placements?.some(item=>item.drive_id===drive));
 return <div className="coach-page"><PageHeading eyebrow="YOUR PERSONAL TRAINING ROOM" title="AI Coach">Build a focused plan, talk naturally with your coach, and strengthen the areas that matter for your next attempt.</PageHeading>{error&&<ErrorMessage message={error}/>}
 <section className="coach-hero panel"><div className="coach-avatar coach-avatar-photo" aria-hidden="true"><img src="/assets/panel/stills/neha-v3-idle.png" alt=""/><i/><i/><i/></div><div><span className="eyebrow"><Sparkles size={14}/> VOICEDOT COACH</span><h2>Meet your role preparation coach</h2><p>Choose a placement opportunity and the coach will use its role, JD, and any released feedback from your completed attempt to build the next plan.</p><div className="coach-capabilities"><span><Mic size={16}/> Voice lessons</span><span><MessageCircle size={16}/> Saved discussion</span><span><Target size={16}/> Weak-area training</span></div></div></section>
 <section className="panel coach-main-resume"><div><span className="eyebrow">YOUR STARTING EVIDENCE</span><h2>Main Resume</h2><p>{overview.data?.main_resume?`${overview.data.main_resume.label}${overview.data.main_resume.uploaded_at?` · Saved ${dateTime(overview.data.main_resume.uploaded_at)}`:""}`:"Choose a Main Resume before preparing so the Coach can compare your experience with the placement requirements."}</p></div><Link className="button secondary" to="/profile">{overview.data?.main_resume?"Review Main Resume":"Choose Main Resume"}</Link></section> <section className="panel coach-next-drives"><div className="section-heading"><div><span className="eyebrow">REAL PLACEMENT DATA</span><h2>Prepare for your next opportunity</h2><p>These are drives assigned to you. Select one to use its official role and job description.</p></div><CalendarDays size={24}/></div><div className="coach-drive-cards">{(overview.data?.upcoming_drives||[]).slice(0,4).map(item=><button key={item.drive_id} className={`coach-drive-card ${drive===item.drive_id?'selected':''}`} onClick={()=>void chooseDrive(item.drive_id)}><strong>{item.company_name}</strong><span>{item.role_title}</span><small>{item.window_start_at?dateTime(item.window_start_at):'Date to be confirmed'} · {item.next_action==='CONTINUE_PLAN'?'Continue plan':'Start preparation'}</small></button>)}{!overview.loading&&overview.error&&<ErrorMessage message={overview.error} retry={overview.reload}/>}{!overview.loading&&!overview.error&&!overview.data?.upcoming_drives?.length&&<p className="muted">No upcoming eligible placement drives are available yet.</p>}</div></section>
 {overview.data?.completed_placements?.length ? <section className="panel coach-next-drives"><div className="section-heading"><div><span className="eyebrow">COMPLETED PLACEMENTS</span><h2>Keep preparing for this role</h2><p>Interview feedback appears only after your placement team releases it.</p></div></div><div className="coach-drive-cards">{overview.data.completed_placements.map(item=><article key={item.drive_id} className="coach-drive-card"><strong>{item.company_name}</strong><span>{item.role_title}</span><small>{item.feedback_status==='released'?'Feedback released':'Results awaiting release'}{item.completed_at?` · ${dateTime(item.completed_at)}`:''}</small><button className="button secondary small" onClick={()=>void chooseDrive(item.drive_id)}>{item.has_coaching_plan?'Continue improvement':'Prepare for this role'}</button>{item.feedback_status==='released'&&<Link to="/reports">View feedback</Link>}</article>)}</div></section> : null}
 {recommendation.data?.available&&<section className="panel coach-recommendation"><div><span className="eyebrow">YOUR RELEASED INTERVIEW FEEDBACK</span><h2>Choose whether to practise these areas</h2><p>{recommendation.data.message}</p><div className="focus-chips">{recommendation.data.weak_skills.map((skill,i)=><span key={i}>{skill.focus||'Skill focus'}</span>)}</div>{recommendation.data.cycle&&<div className="coach-cycle-preview"><span><b>1</b>Improvement session saved</span><span><b>2</b>Learn and practise weak skills</span><span><b>3</b>Validate before your next attempt</span></div>}</div>{recommendation.data.cycle?<button className="button primary" onClick={()=>{if(recommendation.data?.plan_id)setSelected(recommendation.data.plan_id)}}>Open improvement plan</button>:!overview.data?.plans?.some(item=>item.drive_id===recommendation.data?.drive_id)?<button className="button primary" onClick={()=>{chooseDrive(recommendation.data?.drive_id||'');document.querySelector('.coach-setup')?.scrollIntoView({behavior:'smooth',block:'start'})}}>Choose improvement target</button>:<button className="button primary" disabled={accepting} onClick={()=>{setAccepting(true);setError('');void api<CoachRecommendation>('/api/student/coach/latest-recommendation/accept',{method:'POST',timeoutMs:COACH_AI_TIMEOUT_MS}).then(()=>{recommendation.reload();overview.reload();cycles.reload()}).catch(e=>setError(e.message)).finally(()=>setAccepting(false))}}>{accepting?'Adding focused sessions…':'Create Improvement Session'}</button>}</section>}
 {readiness.data&&<section className="panel coach-readiness"><div className="section-heading"><div><span className="eyebrow">EVIDENCE BASED</span><h2>Existing skill evidence</h2><p>This history covers prior practice across roles. Use My Placement Skills for the selected role’s full requirement coverage; resume mentions alone do not prove ability.</p></div></div><div className="focus-chips">{readiness.data.skills.map(skill=><span key={skill.skill}>{skill.skill} · {skill.state.replaceAll('_',' ')}</span>)}</div></section>}
 {drive&&<CoachDiagnostic key={drive} driveId={drive} onReady={setDiagnosticReady}/>}
 <div className="coach-layout"><section className="panel coach-setup"><div className="section-heading"><div><span className="eyebrow">YOUR PLACEMENT</span><h2>Create a preparation plan</h2></div><CalendarDays size={24}/></div><form onSubmit={e=>{e.preventDefault();if(!drive||!diagnosticReady){setError('Complete or skip the placement diagnostic first.');return}setBusy(true);setError('');void api<Plan>('/api/student/coach/plans',{...json({drive_id:drive,...(isCompleted?{improvement_target_date:date}:{})}),timeoutMs:180000}).then(p=>{overview.reload();setSelected(p.id)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}><fieldset disabled={busy}>
 <label>Placement opportunity<select required value={drive} onChange={e=>void chooseDrive(e.target.value)}><option value="">Select an eligible placement</option>{overview.data?.upcoming_drives?.map(d=><option key={d.drive_id} value={d.drive_id}>{d.company_name} — {d.role_title}</option>)}{overview.data?.completed_placements?.map(d=><option key={d.drive_id} value={d.drive_id}>{d.company_name} — {d.role_title} (completed)</option>)}</select></label>
 <div className="career-grid"><label>Role<input required minLength={2} maxLength={200} value={role} readOnly/></label><label>Company<input maxLength={200} value={company} readOnly/></label><label>{isCompleted?"Improvement target (not an interview date)":"Interview date"}<input type="date" required value={date} readOnly={!isCompleted} min={isCompleted?indiaDateInput(new Date(Date.now()+86400000).toISOString()):undefined} max={isCompleted?indiaDateInput(new Date(Date.now()+14*86400000).toISOString()):undefined} onChange={e=>setDate(e.target.value)}/><small>{isCompleted?"Choose a goal within 14 days. This does not schedule another interview.":"Set by your placement team."}</small></label></div>{!isCompleted&&<label>Official job description<textarea required minLength={20} maxLength={20000} rows={5} value={jd} readOnly/></label>}{isCompleted&&<p>The Coach uses this placement’s frozen job description. Only released interview feedback is included.</p>}<button className="button primary" disabled={!drive||!diagnosticReady}>{busy?'Building your coaching plan…':isCompleted?'Create improvement plan':'Build preparation plan'}</button></fieldset></form></section>
 <section className="panel coach-plan-picker"><span className="eyebrow">SAVED PLANS</span><h2>Your coaching rooms</h2>{overview.error&&<ErrorMessage message={overview.error} retry={overview.reload}/>}<div className="coach-plan-list">{overview.data?.plans?.map(p=><button aria-label={`${p.role_title} · ${p.target_date?.slice(0,10)}`} aria-pressed={selected===p.id} className="coach-plan-button" key={p.id} onClick={()=>setSelected(p.id)}><span className="mini-coach coach-mark" aria-hidden="true">✦</span><span><strong>{p.role_title}</strong><small>{p.company_name} · {p.target_date?.slice(0,10)}</small></span></button>)}</div>{!overview.loading&&!overview.error&&!overview.data?.plans?.length&&<p>Create a plan to open your first coaching room.</p>}</section></div>
 {selected&&<PlanDetail key={`${selected}:${requestedSession}`} id={selected} sessionId={requestedSession||undefined} recommendation={recommendation.data||undefined} cycle={cycles.data?.cycles.find(item=>item.plan_id===selected)||recommendation.data?.cycle} onEvidenceChange={readiness.reload} onSessionChange={session=>{const next=new URLSearchParams(params);next.set('plan',selected);next.set('session',session);navigate(`/coach?${next.toString()}`,{replace:true})}} onCycle={()=>{cycles.reload();recommendation.reload()}} onDelete={()=>{setSelected('');overview.reload();cycles.reload()}}/>}<p>{selected&&<><Link to={`/coach/skills?plan=${encodeURIComponent(selected)}`}>My Placement Skills</Link> · </>}<Link to="/calendar">View your calendar</Link> · <Link to="/practice">Put your learning into interview practice</Link></p></div>
}

function CoachDiagnostic({driveId,onReady}:{driveId:string;onReady:(ready:boolean)=>void}){
 const [value,setValue]=useState<CoachDiagnostic|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState('');
 const root=`/api/student/coach/drives/${encodeURIComponent(driveId)}/diagnostic`;
 useEffect(()=>{let alive=true;setLoading(true);void api<CoachDiagnostic>(root).then(result=>{if(alive){setValue(result);setAnswers(result.answers_json||{});onReady(result.status==='completed')}}).catch(e=>{if(alive&&!(e instanceof ApiError&&e.status===404))setError((e as Error).message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[root,onReady]);
 useEffect(()=>{if(!dirty||value?.status!=='in_progress')return;const timer=window.setTimeout(()=>{void api(`${root}/answers`,{...json({answers}),method:'PUT'}).catch(e=>setError(`Could not save diagnostic answers: ${(e as Error).message}`))},650);return()=>window.clearTimeout(timer)},[answers,dirty,root,value?.status]);
 async function start(){setBusy(true);setError('');try{const result=await api<CoachDiagnostic>(root,{method:'POST',timeoutMs:COACH_AI_TIMEOUT_MS});setValue(result);setAnswers(result.answers_json||{});onReady(result.status==='completed')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function complete(){setBusy(true);setError('');try{await api(`${root}/answers`,{...json({answers}),method:'PUT'});const result=await api<CoachDiagnostic>(`${root}/complete`,{method:'POST',timeoutMs:COACH_AI_TIMEOUT_MS});setValue(result);setDirty(false);onReady(result.status==='completed')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel coach-diagnostic"><div className="section-heading"><div><span className="eyebrow">FIRST, CHECK WHAT YOU KNOW</span><h2>Placement skills diagnostic</h2><p>Answer independently. You can leave a task blank; it will stay unassessed, not count as a failed answer. Your answers are saved as you work.</p></div><Target size={24}/></div>
 {loading&&<p role="status">Loading your saved diagnostic…</p>}{error&&<ErrorMessage message={error}/>}
 {!loading&&!value&&<button className="button primary" disabled={busy} onClick={()=>void start()}>{busy?'Preparing tasks…':'Assess my placement skills'}</button>}
 {value?.status==='in_progress'&&<><div className="coach-diagnostic-tasks">{value.tasks_json.map((task,index)=><label key={task.task_id}><strong>{index+1}. {task.sub_skill} · {task.format}</strong><span>{task.question}</span><textarea value={answers[task.task_id]||''} onChange={event=>{setAnswers({...answers,[task.task_id]:event.target.value});setDirty(true)}} maxLength={10000} placeholder="Your independent answer, or leave blank for now"/></label>)}</div><button className="button primary" disabled={busy} onClick={()=>void complete()}>{busy?'Checking answers…':'Finish diagnostic'}</button></>}
 {value?.status==='completed'&&<div className="coach-diagnostic-results"><p role="status">Diagnostic saved. These results guide your plan and do not replace independent skill validation.</p>{value.result_json?.skills.map(item=><span key={item.skill}>{item.skill}: {item.state.replaceAll('_',' ')} · {item.demonstrated_tasks}/{item.assessed_tasks} demonstrated</span>)}</div>}
 </section>
}
function PlanDetail({id,sessionId,recommendation,cycle,onEvidenceChange,onSessionChange,onCycle,onDelete}:{id:string;sessionId?:string;recommendation?:CoachRecommendation;cycle?:CoachCycle;onEvidenceChange:()=>void;onSessionChange:(sessionId:string)=>void;onCycle:()=>void;onDelete:()=>void}){
 const navigate=useNavigate();
 const resource=useResource<Plan>(`/api/student/coach/plans/${id}${sessionId?`?session_id=${encodeURIComponent(sessionId)}`:''}`),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[snapshot,setSnapshot]=useState<Plan|null>(null),[exchange,setExchange]=useState<{student:string;coach:string}|null>(null),[booking,setBooking]=useState(''),[bookingTime,setBookingTime]=useState(localDateTime()),[bookingMinutes,setBookingMinutes]=useState('45');const p=resource.data||snapshot;useEffect(()=>{if(resource.data)setSnapshot(resource.data)},[resource.data]);useEffect(()=>{if(exchange&&resource.data?.messages?.some(item=>item.content===exchange.coach)&&resource.data.messages.some(item=>item.role==='student'&&item.content===exchange.student))setExchange(null)},[resource.data,exchange]);
 async function saveSchedule(targetSession:string,remove=false){setBusy(true);setError('');try{await api(`/api/student/coach/plans/${encodeURIComponent(id)}/sessions/${encodeURIComponent(targetSession)}/schedule`,remove?{method:'DELETE'}:{...json({scheduled_for:new Date(bookingTime).toISOString(),duration_minutes:Number(bookingMinutes)}),method:'PUT'});setBooking('');resource.reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function send(text:string){if(!text.trim()||busy)return;setBusy(true);setError('');try{const result=await api<{reply:string}>(`/api/student/coach/plans/${id}/messages`,{...json({message:text,session_id:sessionId||null}),timeoutMs:20000});setExchange({student:text,coach:result.reply});setMessage('');resource.reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="coach-room">{(error||resource.error)&&<ErrorMessage message={error||resource.error} retry={resource.reload}/>} {p&&<><header className="panel coach-room-header"><div className="mini-coach large coach-mark" aria-hidden="true">✦</div><div><span className="eyebrow">ACTIVE COACHING PLAN</span><h2>{p.role_title}</h2><p>{p.company_name} · Target {p.target_date?.slice(0,10)}</p></div><div className="career-actions"><button className="button secondary" onClick={()=>void download(`/api/student/coach/plans/${id}/pdf`,'Preparation-plan.pdf').catch(e=>setError(e.message))}>Download plan</button><button className="text-button" disabled={busy} onClick={()=>{if(confirm('Delete this preparation plan and its conversation?')){setBusy(true);void api(`/api/student/coach/plans/${id}`,{method:'DELETE'}).then(onDelete).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}}>Delete</button></div></header>
 {p.context_status?.main_resume_changed&&<div className="coach-context-alert" role="status">Your Main Resume changed since this plan was created. Review your preparation against the new resume; saved diagnostic answers and lessons are preserved.</div>} {p.plan.source_context?.deadline_at&&<p className="coach-deadline-note">Preparation deadline: {dateTime(p.plan.source_context.deadline_at)} IST. This uses the official interview window start until your placement team confirms an individual appointment.</p>}{p.plan.deadline_notice&&<div className="coach-context-alert" role="status">{p.plan.deadline_notice}{p.plan.uncovered_topics?.length?` Still to assess: ${p.plan.uncovered_topics.join(", ")}.`:""}</div>} <TrainingCycle planId={id} recommendation={recommendation} cycle={cycle} onChange={onCycle} onError={setError}/>
 <section className="panel"><h3>{p.plan.goal}</h3><p>{p.plan.summary}</p><div className="coach-topic-grid">{p.plan.priority_topics.map((t,i)=><article className="coach-topic" key={i}><span className={`priority priority-${t.priority}`}>{t.priority}</span><h3>{t.topic}</h3><p>{t.why}</p><div><CheckCircle2 size={16}/><span>{t.outcome}</span></div></article>)}</div></section>
 <CoachLifecycle planId={id} plan={p} studentTurnCount={p.messages?.filter(message=>message.role==='student').length||0} sessionId={sessionId} onError={setError} onSessionChange={onSessionChange} onRefresh={()=>{resource.reload();onEvidenceChange()}}/>
 <section className="panel"><div className="section-heading"><div><span className="eyebrow">YOUR PREPARATION PLAN</span><h3>Book your sessions</h3><p>Lessons appear on your Calendar only after you choose and confirm a time.</p></div><CalendarDays size={24}/></div><div className="roadmap-calendar">{p.plan.daily_roadmap.map(d=>{const daySessionId=d.session_id||`${p.id}:day:${d.day}`;const scheduled=!!d.planned_at&&d.schedule_status!=='cancelled';return <article key={daySessionId} className={`roadmap-day${sessionId===daySessionId?' selected':''}`}><header><span>{d.day}</span><div><small>{scheduled?`${dateTime(d.planned_at!)} · ${d.duration_minutes||45} minutes`:'Not scheduled'}{d.session_type==='retraining'?' · Focused retraining':''}</small><strong>{d.title}</strong></div></header><p>{d.focus}</p><ul>{d.activities.map((a,j)=><li key={j}>{a}</li>)}</ul><footer><CheckCircle2 size={15}/> {d.success_check}</footer><div className="career-actions"><button className="button secondary small" onClick={()=>onSessionChange(daySessionId)}>Open lesson</button><button className="button secondary small" onClick={()=>{setBooking(daySessionId);if(scheduled)setBookingTime(new Date(new Date(d.planned_at!).getTime()-new Date(d.planned_at!).getTimezoneOffset()*60000).toISOString().slice(0,16))}}>{scheduled?'Reschedule':'Create session'}</button>{scheduled&&<button className="text-button" disabled={busy} onClick={()=>void saveSchedule(daySessionId,true)}>Cancel booking</button>}</div>{booking===daySessionId&&<div className="coach-schedule-fields"><label>Date and time<input type="datetime-local" min={localDateTime(0)} value={bookingTime} onChange={event=>setBookingTime(event.target.value)}/></label><label>Duration<select value={bookingMinutes} onChange={event=>setBookingMinutes(event.target.value)}><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option></select></label><button className="button primary small" disabled={busy||!bookingTime} onClick={()=>void saveSchedule(daySessionId)}>Confirm session</button><button className="button secondary small" onClick={()=>setBooking('')}>Back</button></div>}</article>})}</div></section>
 </>}
 <section className="coach-voice-launch"><div><span className="eyebrow">LIVE AI COACH</span><h3>Connect with Neha</h3><p>{sessionId?'Neha will open this exact session with its skill and learning objective.':'Select a calendar session first so the Coach opens with the right context.'}</p></div><button className="button primary" disabled={!sessionId} onClick={()=>navigate(`/coach/session?plan=${encodeURIComponent(id)}&session=${encodeURIComponent(sessionId||'')}`)}><Mic size={17}/> Connect</button></section>
 <section className="panel coach-chat"><div className="section-heading"><div><span className="eyebrow">CONTINUE THE LESSON</span><h3>Chat with your coach</h3></div><MessageCircle size={23}/></div><div className="coach-messages" aria-label="Saved coach conversation">{p?.messages?.map((m,i)=><article key={m.id||i} className={`coach-message ${m.role==='student'?'student':''}`}><span className="message-avatar">{m.role==='student'?'You':'✦'}</span><div><strong>{m.role==='student'?'You':'AI Coach'}</strong><p>{m.content}</p></div></article>)}{exchange&&[exchange.student,exchange.coach].map((content,index)=><article key={`latest-${index}`} className={`coach-message ${index===0?'student':''}`}><span className="message-avatar">{index===0?'You':'✦'}</span><div><strong>{index===0?'You':'AI Coach'}</strong><p>{content}</p></div></article>)}</div>
 <div className="coach-starters">{p?.plan.discussion_starters?.map((s,i)=><button className="text-button" disabled={busy} key={i} onClick={()=>void send(s)}>{s}</button>)}</div><form className="coach-compose" onSubmit={e=>{e.preventDefault();void send(message)}}><textarea aria-label="Ask your coach" required maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask for an explanation, example, or what to study next…"/><button className="button primary" disabled={busy||!p}>{busy?'Coach is thinking…':'Send message'}</button></form></section>
 </section>
}

function CoachLifecycle({planId,plan,studentTurnCount,sessionId,onError,onSessionChange,onRefresh}:{planId:string;plan:Plan;studentTurnCount:number;sessionId?:string;onError:(message:string)=>void;onSessionChange:(sessionId:string)=>void;onRefresh:()=>void}){
 const state=useResource<any>(sessionId?`/api/student/coach/plans/${encodeURIComponent(planId)}/sessions/${encodeURIComponent(sessionId)}`:null);
 const [busy,setBusy]=useState(false),[response,setResponse]=useState(''),[hints,setHints]=useState<any[]>([]),[answers,setAnswers]=useState<Record<string,string>>({}),[blockedAtTurnCount,setBlockedAtTurnCount]=useState<number|null>(null);
 const current=state.data,stage=String(current?.stage||''),roadmap=plan.plan.daily_roadmap.find(item=>item.session_id===sessionId),skill=current?.skill||roadmap?.skill||roadmap?.focus||plan.role_title;
 useEffect(()=>{if(sessionId&&(state.error||state.data?.stage==='pending')&&!busy){setBusy(true);void api(`/api/student/coach/plans/${encodeURIComponent(planId)}/sessions/${encodeURIComponent(sessionId)}`,{method:'POST',...json({}),timeoutMs:COACH_AI_TIMEOUT_MS}).then(()=>state.reload()).catch(e=>onError((e as Error).message)).finally(()=>setBusy(false))}},[state.error,state.data?.stage,planId,sessionId,busy]);
 useEffect(()=>{setHints(current?.practice_hints||[]);const saved=Object.fromEntries((current?.validation_draft||[]).map((item:any)=>[item.task_id,item.response]));setAnswers(saved)},[current?.id,current?.stage,current?.practice_hints,current?.validation_draft]);
 if(!sessionId)return <section className="panel coach-lifecycle"><h3>Select a preparation session</h3><p>Choose a roadmap session above or open one from Calendar to continue.</p></section>;
 async function transition(path:string,body:unknown){if(busy||!sessionId)return;setBusy(true);onError('');try{await api(`/api/student/coach/plans/${encodeURIComponent(planId)}/sessions/${encodeURIComponent(sessionId)}/${path}`,{...json(body),timeoutMs:COACH_AI_TIMEOUT_MS});setResponse('');setBlockedAtTurnCount(null);await state.reload();onRefresh()}catch(e){if(path==='teaching'&&e instanceof ApiError&&e.status===409)setBlockedAtTurnCount(studentTurnCount);onError((e as Error).message)}finally{setBusy(false)}}
 async function getHint(){if(!current?.practice_task?.question||busy||!sessionId)return;setBusy(true);onError('');try{const result=await api<any>(`/api/student/coach/plans/${encodeURIComponent(planId)}/sessions/${encodeURIComponent(sessionId)}/practice/hint`,{...json({task:current.practice_task.question,skill}),timeoutMs:COACH_AI_TIMEOUT_MS});setHints(result.session?.practice_hints||[...hints,{level:result.level,content:result.hint}]);await state.reload()}catch(e){onError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(stage!=='validation'||!current?.validation_tasks?.length)return;const timer=setTimeout(()=>{const draft=current.validation_tasks.filter((task:any)=>answers[task.task_id]!==undefined).map((task:any)=>({task_id:task.task_id,response:answers[task.task_id]}));void api(`/api/student/coach/plans/${encodeURIComponent(planId)}/sessions/${encodeURIComponent(sessionId)}/validation/answers`,{method:'PUT',...json({answers:draft})}).catch(e=>onError((e as Error).message))},400);return()=>clearTimeout(timer)},[stage,answers,planId,sessionId,current?.validation_tasks]);
 const practiceTask=current?.practice_task?.question||'';
 const validationTasks=current?.validation_tasks||[];
 return <section className="panel coach-lifecycle"><div className="section-heading"><div><span className="eyebrow">CURRENT COACH SESSION</span><h3>{skill}</h3><p>{plan.company_name} · {plan.role_title}</p></div><span className="pill">{stage?stage.replaceAll('_',' '):'Loading'}</span></div>{state.error&&<ErrorMessage message={state.error} retry={state.reload}/>} {current&&<><p><strong>Learning objective:</strong> {current.learning_objective||roadmap?.success_check||roadmap?.focus}</p><p className="muted"><strong>Skill state:</strong> {(current.skill_state||'unassessed').replaceAll('_',' ')}</p>
 {stage==='teaching'&&<><p>Connect with Neha or use the session chat for its lesson and diagnostic. Teaching completion is checked against the saved conversation.</p><button className="button primary" disabled={busy||studentTurnCount<2||blockedAtTurnCount===studentTurnCount} onClick={()=>void transition('teaching',{learning_objective:current.learning_objective})}>{busy?'Checking lesson…':'Complete Teaching'}</button><small>{studentTurnCount<2?`${studentTurnCount} of 2 saved student responses. Continue the lesson in the chat before checking completion.`:blockedAtTurnCount===studentTurnCount?'Add another response to the saved conversation, then try again.':`At least two student responses and coverage of the learning objective are required before practice opens. ${studentTurnCount} responses saved.`}</small></>}
 {(stage==='practice'||stage==='needs_additional_practice')&&<div className="coach-practice"><h4>{stage==='needs_additional_practice'?'More practice is needed':'Guided practice'}</h4>{current.practice?.feedback&&<p role="status">{current.practice.feedback}</p>}{stage==='needs_additional_practice'&&<button className="button secondary" disabled={busy} onClick={()=>void transition('practice/task',{skill,sub_skill:current.practice?.sub_skill||skill})}>Get a new practice task</button>}{practiceTask&&<p><strong>Task:</strong> {practiceTask}</p>}<div className="focus-chips">{hints.map((hint:any,index:number)=><span key={`${hint.level}-${index}`}>{hint.level.replaceAll('_',' ')}: {hint.content}</span>)}</div><button className="button secondary" disabled={busy||hints.length>=3||!practiceTask} onClick={()=>void getHint()}>{hints.length>=3?'All hints used':`Get hint ${hints.length+1} of 3`}</button><label>Your response<textarea value={response} onChange={event=>setResponse(event.target.value)} placeholder="Work through the task in your own words…"/></label><button className="button primary" disabled={busy||!response.trim()||!practiceTask} onClick={()=>void transition('practice',{task:practiceTask,response,skill})}>{busy?'Evaluating…':'Submit Practice'}</button></div>}
 {stage==='ready_for_validation'&&<><p>Practice is complete. Validation uses fresh tasks and independent answers without hints.</p><button className="button primary" disabled={busy} onClick={()=>void transition('validation/start',{skill,required_sub_skills:[current.practice?.sub_skill||skill]})}>Start Validation</button></>}
 {stage==='validation'&&<div className="coach-validation"><p>Independent assessment: these tasks are generated separately from your recent practice. You can skip a task without claiming you demonstrated it.</p>{current.validation?.status==='needs_review'&&<p role="status">The evidence was uncertain or incomplete. Review your answers and retry; this skill has not been marked as demonstrated.</p>}{current.validation?.status==='unassessed'&&<p role="status">These tasks remain unassessed. Answer them when you are ready.</p>}{validationTasks.map((task:any,index:number)=><label key={task.task_id} className="block"><strong>{index+1}. {task.sub_skill} · {task.format}</strong><span>{task.question}</span><textarea value={answers[task.task_id]||''} onChange={event=>setAnswers({...answers,[task.task_id]:event.target.value})} placeholder="Answer without hints. Your draft is saved automatically."/><button type="button" className="button secondary small" onClick={()=>setAnswers({...answers,[task.task_id]:''})}>Skip this task</button>{answers[task.task_id]===''&&<small>Skipped. This will remain unassessed.</small>}</label>)}<button className="button primary" disabled={busy||!validationTasks.length||validationTasks.some((task:any)=>answers[task.task_id]===undefined)} onClick={()=>void transition('validation',{answers:validationTasks.map((task:any)=>({task_id:task.task_id,response:answers[task.task_id]}))})}>{busy?'Checking evidence…':'Submit Validation'}</button></div>}
 {stage==='retraining'&&<><p>Validation found gaps in: {(current.validation?.weak_sub_skills||[]).join(', ')||'this skill'}. Focused retraining lessons are suggested below. Choose a time for each lesson to put it on your Calendar.</p>{(current.validation?.weak_sub_skills||[]).map((weak:string)=><button className="button primary" key={weak} onClick={()=>{const next=plan.plan.daily_roadmap.find(item=>item.session_type==='retraining'&&item.focus===weak);if(next?.session_id)onSessionChange(next.session_id)}}>Start retraining: {weak}</button>)}</>}
 {stage==='completed'&&<div role="status" className="success-message">{current.validation?.status==='validated'?'Validated with independent evidence.':`Validation result: ${(current.validation?.status||'completed').replaceAll('_',' ')}`}</div>}</>}</section>
}

function localDateTime(hours=1){const value=new Date(Date.now()+hours*3600000);value.setMinutes(value.getMinutes()-value.getTimezoneOffset());return value.toISOString().slice(0,16)}
function TrainingCycle({planId,recommendation,cycle,onChange,onError}:{planId:string;recommendation?:CoachRecommendation;cycle?:CoachCycle;onChange:()=>void;onError:(value:string)=>void}){
 const [callAt,setCallAt]=useState(localDateTime()),[callMinutes,setCallMinutes]=useState('10'),[interviewAt,setInterviewAt]=useState(localDateTime(25)),[interviewMinutes,setInterviewMinutes]=useState('30'),[difficulty,setDifficulty]=useState('intermediate'),[busy,setBusy]=useState(false);
 async function scheduleCall(){setBusy(true);onError('');try{await api('/api/student/coach/training-cycles',{...json({plan_id:planId,source_evaluation_id:recommendation?.evaluation_id||null,scheduled_for:new Date(callAt).toISOString(),duration_minutes:Number(callMinutes)})});onChange()}catch(e){onError((e as Error).message)}finally{setBusy(false)}}
 async function scheduleInterview(){if(!cycle)return;setBusy(true);onError('');try{await api(`/api/student/coach/training-cycles/${encodeURIComponent(cycle.id)}/interview`,{...json({scheduled_for:new Date(interviewAt).toISOString(),duration_minutes:Number(interviewMinutes),difficulty})});onChange()}catch(e){onError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel coach-cycle"><div className="section-heading"><div><span className="eyebrow">COACHING CYCLE</span><h3>Learn, practise, then interview again</h3></div><span className="pill">{cycle?.practice_status||'Plan ready'}</span></div><div className="coach-cycle-steps"><article className={cycle?'complete':'active'}><b>1</b><div><strong>Schedule coaching call</strong>{cycle?<p>{dateTime(cycle.call_scheduled_for)} · {cycle.call_duration_minutes} minutes</p>:<div className="coach-schedule-fields"><label>Call time<input type="datetime-local" min={localDateTime(0)} value={callAt} onChange={e=>setCallAt(e.target.value)}/></label><label>Length<select value={callMinutes} onChange={e=>setCallMinutes(e.target.value)}><option value="10">10 minutes</option><option value="20">20 minutes</option></select></label><button className="button primary small" disabled={busy||!callAt} onClick={()=>void scheduleCall()}>Schedule call</button></div>}</div></article><article className={cycle?.call_completed_at?'complete':cycle?'active':''}><b>2</b><div><strong>Teaching and guided practice</strong><p>{cycle?.call_completed_at?'Coach call completed. Your focused practice interview is unlocked.':cycle?'Your focused session is ready. Connect here or open it from Calendar.':'Complete step 1 to open your teaching room.'}{cycle&&!cycle.call_completed_at&&<Link className="button primary small" to={`/coach/session?plan=${encodeURIComponent(planId)}&cycle=${encodeURIComponent(cycle.id)}`}>Connect AI Coach</Link>}</p></div></article><article className={cycle?.practice_status==='scheduled'||cycle?.practice_status==='started'?'complete':cycle?.call_completed_at?'active':''}><b>3</b><div><strong>Focused AI interview</strong>{cycle?.interview_scheduled_for?<><p>{dateTime(cycle.interview_scheduled_for)} · {cycle.interview_duration_minutes} minutes · {cycle.interview_difficulty}</p><Link className="button primary small" to={`/practice?coach_cycle=${encodeURIComponent(cycle.id)}`}>Start practice interview</Link></>:cycle?.call_completed_at?<div className="coach-schedule-fields"><label>Interview time<input type="datetime-local" min={localDateTime(0)} value={interviewAt} onChange={e=>setInterviewAt(e.target.value)}/></label><label>Length<select value={interviewMinutes} onChange={e=>setInterviewMinutes(e.target.value)}><option value="30">30 minutes</option><option value="45">45 minutes</option></select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><button className="button primary small" disabled={busy||!interviewAt} onClick={()=>void scheduleInterview()}>Schedule interview</button></div>:<p>Complete the teaching call to unlock this step.</p>}</div></article></div></section>
}
