import { useEffect, useRef, useState } from 'react';
import { api, json } from './api';
import { Dialog } from './ui';

type Candidate={question_text:string;round_type:string;canonical_skill?:string|null;difficulty?:string|null};
type RecognitionResult={isFinal?:boolean;[index:number]:{transcript?:string}};
type RecognitionEvent={resultIndex:number;results:ArrayLike<RecognitionResult>};
type RecognitionLike={continuous:boolean;interimResults:boolean;lang:string;onresult:((event:RecognitionEvent)=>void)|null;onerror:((event:{error?:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
type RecognitionCtor=new()=>RecognitionLike;
declare global { interface Window { SpeechRecognition?:RecognitionCtor; webkitSpeechRecognition?:RecognitionCtor } }

export function CoachQuestionContribution({driveId,company,role}:{driveId:string;company:string;role:string}){
 const recognitionRef=useRef<RecognitionLike|null>(null);useEffect(()=>()=>{if(recognitionRef.current){recognitionRef.current.onend=null;recognitionRef.current.stop()}},[]);
 const [open,setOpen]=useState(false),[mode,setMode]=useState<'choose'|'voice'|'manual'>('choose'),[transcript,setTranscript]=useState(''),[candidates,setCandidates]=useState<Candidate[]>([]),[manual,setManual]=useState(''),[confirmed,setConfirmed]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 function close(){if(recognitionRef.current){recognitionRef.current.onend=null;recognitionRef.current.stop();recognitionRef.current=null}setOpen(false);setMode('choose');setTranscript('');setCandidates([]);setManual('');setConfirmed(false);setError('')}
 async function extract(text:string){setTranscript(text);setWorking(true);setError('');try{const result=await api<{candidates:Candidate[]}>(`/api/student/coach/drives/${encodeURIComponent(driveId)}/question-contribution/extract`,{...json({transcript:text})});setCandidates(result.candidates);setMode('voice')}catch(reason){setError((reason as Error).message)}finally{setWorking(false)}}
 function speak(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setError('Speech recognition is unavailable in this browser. Add the questions manually instead.');return}setError('');setMode('voice');recognitionRef.current?.stop();const recognition=new Recognition();recognitionRef.current=recognition;recognition.continuous=true;recognition.interimResults=false;recognition.lang='en-IN';let text='';recognition.onresult=event=>{for(let index=event.resultIndex;index<event.results.length;index++)if(event.results[index].isFinal)text+=`${event.results[index][0].transcript} `;setTranscript(text.trim())};recognition.onerror=event=>setError(event.error==='not-allowed'?'Microphone access was denied. You can add questions manually.':'Speech recognition stopped. You can retry or add questions manually.');recognition.onend=()=>{if(text.trim())void extract(text.trim())};try{recognition.start()}catch(reason){setError((reason as Error).message)}}
 function addManual(){const text=manual.trim();if(!text)return;setCandidates(rows=>[...rows,{question_text:text,round_type:'Technical'}]);setManual('');setMode('manual')}
 async function save(){if(!confirmed||!candidates.length||working)return;setWorking(true);setError('');try{const result=await api<{count:number}>(`/api/student/coach/drives/${encodeURIComponent(driveId)}/question-contribution`,{method:'POST',...json({confirmed:true,questions:candidates.filter(row=>row.question_text.trim())})});setSaved(`Thanks. ${result.count} question${result.count===1?'':'s'} added for ${company} · ${role}. They are marked as student reported.`);close()}catch(reason){setError((reason as Error).message)}finally{setWorking(false)}}
 return <><button type="button" className="coach-secondary coach-contribute-trigger" onClick={()=>{setOpen(true);setSaved('')}}>Help future students prepare</button>{saved&&<p className="coach-contribution-saved" role="status">{saved}</p>}{open&&<Dialog labelledBy="coach-contribution-title" close={close} className="coach-contribution-dialog"><button className="coach-contribution-close" aria-label="Close" onClick={close}>×</button><div className="coach-card-kicker">COMPLETED PLACEMENT · {company}</div><h2 id="coach-contribution-title">What questions were you asked?</h2><p>Share questions from your completed {role} interview to help future students. Your identity is not shown with the questions.</p>{mode==='choose'&&<div className="coach-contribution-choice"><button className="coach-primary" onClick={speak}>Speak questions</button><button className="coach-secondary" onClick={()=>setMode('manual')}>Add manually</button></div>}{mode==='voice'&&<><div className="coach-contribution-choice"><button className="coach-primary" disabled={working} onClick={speak}>{working?'Extracting transcript…':'Speak questions'}</button><button className="coach-secondary" onClick={()=>setMode('manual')}>Add manually</button></div>{transcript&&<label className="coach-contribution-transcript">Transcript<textarea value={transcript} onChange={event=>setTranscript(event.target.value)}/></label>}{working&&<p role="status">Finding question spans in your transcript…</p>}</>}{mode==='manual'&&<><label className="coach-contribution-transcript">Question<textarea value={manual} onChange={event=>setManual(event.target.value)} placeholder="Enter a question you were asked"/></label><button className="coach-secondary" disabled={!manual.trim()} onClick={addManual}>Add question</button></>}{candidates.length>0&&<div className="coach-contribution-candidates"><strong>Review and edit before confirming</strong>{candidates.map((item,index)=><label key={index}>Question {index+1}<textarea value={item.question_text} onChange={event=>setCandidates(rows=>rows.map((row,rowIndex)=>rowIndex===index?{...row,question_text:event.target.value}:row))}/></label>)}</div>}{error&&<p role="alert">{error}</p>}{candidates.length>0&&<><label className="coach-contribution-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I confirm these are questions I was asked in this placement interview.</label><button className="coach-primary" disabled={!confirmed||!candidates.some(item=>item.question_text.trim())||working} onClick={()=>void save()}>{working?'Saving…':'Confirm and submit'}</button></>}</Dialog>}</>;
}
