import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, MessageSquareText, Search, X } from 'lucide-react';
import { api, json } from './api';

export type PreviousQuestion = {
  id: string; question_text: string; round_type: string; canonical_skill?: string | null;
  difficulty?: string | null; year?: number | null; interview_date?: string | null;
  report_count: number; last_reported_at?: string | null; source_type?: string; verified?: boolean;
};
type PracticeResult={question_id:string;question_text:string;score:number;status:string;strengths:string[];missing_points:string[];improved_answer_guidance:string};
type QuestionList = { company_name: string; role_name: string; questions: PreviousQuestion[]; count: number; progress?:Record<string,{status:string;score:number|null;attempts:number}> };
const sourceLabel = (source?: string) => ({ PLACEMENT_TEAM: 'Placement team', VERIFIED_PUBLIC_SOURCE: 'Verified public source', STUDENT_REPORTED: 'Candidate reported' } as Record<string, string>)[source || ''] || 'Reported source';
function lastSeen(year?: number | null, value?: string | null) { if (year) return String(year); if (!value) return 'Date unavailable'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Date unavailable' : new Intl.DateTimeFormat('en', { year: 'numeric', month: 'short' }).format(date); }

export function CoachPreviousQuestions({ driveId, company, role, onPractice, compact = false }: {
  driveId: string; company: string; role: string; onPractice: (question: PreviousQuestion) => void; compact?: boolean;
}) {
  const [open, setOpen] = useState(false), [result, setResult] = useState<QuestionList | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState(''), [search, setSearch] = useState(''), [round, setRound] = useState('All'), [skill,setSkill]=useState('All'),[year,setYear]=useState('All'),[source,setSource]=useState('All'),[difficulty,setDifficulty]=useState('All'),[sort,setSort]=useState('reported'),[practice,setPractice]=useState<PreviousQuestion|null>(null),[answer,setAnswer]=useState(''),[practiceBusy,setPracticeBusy]=useState(false),[practiceError,setPracticeError]=useState(''),[practiceResult,setPracticeResult]=useState<PracticeResult|null>(null);
  async function load() { setLoading(true); setError(''); try { const value = await api<QuestionList>(`/api/student/coach/drives/${encodeURIComponent(driveId)}/previous-questions`); setResult(value); } catch (reason) { setError((reason as Error).message || 'Previous interview questions couldn’t be loaded.'); } finally { setLoading(false); } }
  useEffect(() => { if (open && !result && !loading && !error) void load(); }, [open, driveId]);
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [open]);
  const questions = result?.questions || [];
  const roundTypes = useMemo(() => ['All', ...new Set(questions.map(item => item.round_type).filter(Boolean))], [questions]);
  const skills=useMemo(()=>['All',...new Set(questions.map(item=>item.canonical_skill||'').filter(Boolean))],[questions]),years=useMemo(()=>['All',...new Set(questions.map(item=>String(item.year||item.interview_date?.slice(0,4)||'')).filter(value=>value.length===4))].sort((a,b)=>a==='All'?-1:b==='All'?1:b.localeCompare(a)),[questions]),sources=useMemo(()=>['All',...new Set(questions.map(item=>item.source_type||'Reported source'))],[questions]),difficulties=useMemo(()=>['All',...new Set(questions.map(item=>item.difficulty||'').filter(Boolean))],[questions]);
  const filtered = useMemo(()=>questions.filter(item => (round === 'All' || item.round_type === round) && (skill==='All'||item.canonical_skill===skill) && (year==='All'||String(item.year||item.interview_date?.slice(0,4)||'')===year) && (source==='All'||(item.source_type||'Reported source')===source) && (difficulty==='All'||item.difficulty===difficulty) && (!search || `${item.question_text} ${item.canonical_skill || ''}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='reported'?b.report_count-a.report_count:new Date(b.last_reported_at||b.interview_date||`${b.year||0}-01-01`).getTime()-new Date(a.last_reported_at||a.interview_date||`${a.year||0}-01-01`).getTime()),[questions,round,skill,year,source,difficulty,search,sort]);
  return <>
    <div className={`coach-previous-questions${compact ? ' compact' : ''}`}><button type="button" className="coach-secondary" aria-expanded={open} onClick={() => setOpen(true)}><MessageSquareText size={16} /> Previous Interview Questions</button></div>
    {open && <div className="coach-question-drawer-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setOpen(false); }}>
      <aside className="coach-question-drawer" role="dialog" aria-modal="true" aria-label="Previous Interview Questions">
        <header className="coach-question-drawer-header"><div><div className="coach-card-kicker">PLACEMENT INTERVIEW HISTORY</div><h2>Previous Interview Questions</h2><p>{result?.company_name || company} · {result?.role_name || role}</p>{!loading && !error && result && <small>{result.count} {result.count === 1 ? 'question' : 'questions'} reported from previous candidate interviews</small>}</div><button type="button" className="coach-question-drawer-close" aria-label="Close previous interview questions" onClick={() => setOpen(false)}><X size={19}/></button></header>
        {loading && <p role="status" className="coach-question-drawer-state">Loading previous interview questions...</p>}
        {error && <div className="coach-question-drawer-state" role="alert"><p>Previous interview questions couldn’t be loaded.</p><button type="button" className="coach-secondary" onClick={() => void load()}>Retry</button></div>}
        {!loading && !error && result?.count === 0 && <div className="coach-question-drawer-state"><h3>No previous interview questions are available for {result.company_name} · {result.role_name} yet.</h3><p>Questions reported from completed candidate interviews will appear here once available.</p></div>}
        {!loading && !error && result && result.count > 0 && <><label className="coach-question-search"><Search size={17}/><input aria-label="Search questions" placeholder="Search questions..." value={search} onChange={event => setSearch(event.target.value)}/></label><div className="coach-question-filters"><select aria-label="Round" value={round} onChange={e=>setRound(e.target.value)}>{roundTypes.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Skill" value={skill} onChange={e=>setSkill(e.target.value)}>{skills.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Year" value={year} onChange={e=>setYear(e.target.value)}>{years.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Source or status" value={source} onChange={e=>setSource(e.target.value)}>{sources.map(item=><option key={item} value={item}>{item==='All'?'All sources':item==='STUDENT_REPORTED'?'Student Reported':item==='VERIFIED_PUBLIC_SOURCE'?'Verified source':sourceLabel(item)}</option>)}</select><select aria-label="Difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{difficulties.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Sort questions" value={sort} onChange={e=>setSort(e.target.value)}><option value="reported">Most Reported</option><option value="recent">Recently Seen</option></select></div>
          <div className="coach-question-drawer-list">{filtered.map(item => <article className="coach-question-drawer-card" key={item.id}><div className="coach-question-card-top"><span>{item.round_type}</span><span>{sourceLabel(item.source_type)}</span>{item.verified&&<span>Verified</span>}</div><h3>{item.question_text}</h3><div className="coach-question-meta">{item.canonical_skill && <span><strong>{item.canonical_skill}</strong></span>}{item.difficulty && <span>{item.difficulty}</span>}<span>Reported in {item.report_count} {item.report_count === 1 ? 'interview' : 'interviews'}</span><span>Last seen: {lastSeen(item.year, item.last_reported_at||item.interview_date)}</span></div><div className="coach-question-actions"><button type="button" className="coach-primary" onClick={() => { onPractice(item);setOpen(false); }}>{'Practice with AI Coach'} <ArrowRight size={15}/></button><button type="button" className="coach-secondary" onClick={() => { setPractice(item);setPracticeResult(null);setAnswer('');setPracticeError(''); }}>{result.progress?.[item.id]?.status?'Retry evaluation':'Evaluate answer'}</button>{result.progress?.[item.id]&&<small>{result.progress[item.id].status.replace('_',' ')} · score {result.progress[item.id].score??'—'}</small>}</div></article>)}{!filtered.length && <p className="coach-question-drawer-state">No questions match this search.</p>}</div></>}
      </aside>
    </div>}
    {practice&&<div className="coach-question-practice-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setPractice(null)}}><section role="dialog" aria-modal="true" aria-label="Practice previous interview question" className="coach-question-practice"><button className="coach-question-drawer-close" aria-label="Close practice" onClick={()=>setPractice(null)}><X size={18}/></button><small>Historical question · {practice.round_type}{practice.canonical_skill?` · ${practice.canonical_skill}`:''}</small><h2>{practice.question_text}</h2>{!practiceResult?<><label>Your answer<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Write your answer to this exact reported question…"/></label>{practiceError&&<p role="alert">{practiceError}</p>}<button className="coach-primary" disabled={!answer.trim()||practiceBusy} onClick={()=>{setPracticeBusy(true);void api<PracticeResult>(`/api/student/coach/drives/${encodeURIComponent(driveId)}/previous-questions/${encodeURIComponent(practice.id)}/practice`,{...json({answer}),method:'POST'}).then(value=>{setPracticeResult(value);void load()}).catch(reason=>setPracticeError((reason as Error).message)).finally(()=>setPracticeBusy(false))}}>{practiceBusy?'Evaluating…':'Evaluate answer'}</button></>:<><div className="coach-question-practice-score"><strong>{practiceResult.score}</strong><span>Practice score · {practiceResult.status.replace('_',' ')}</span></div><div className="coach-question-practice-columns"><section><h3>Strengths</h3>{practiceResult.strengths.map((item,index)=><p key={index}>{item}</p>)}</section><section><h3>Missing points</h3>{practiceResult.missing_points.map((item,index)=><p key={index}>{item}</p>)}</section></div><section className="coach-question-guidance"><h3>Improved answer guidance</h3><p>{practiceResult.improved_answer_guidance}</p></section><div className="coach-question-actions"><button className="coach-secondary" onClick={()=>{setPracticeResult(null);setAnswer('')}}>Retry</button><button className="coach-primary" onClick={()=>{const index=filtered.findIndex(item=>item.id===practice.id);setPractice(filtered[(index+1)%Math.max(1,filtered.length)]||null);setPracticeResult(null);setAnswer('')}}>Next Previous Question</button></div></>}</section></div>}
  </>;
}
