import { useEffect, useState } from 'react';
import { Bot, CalendarDays, CheckCircle2, MessageCircle, Mic, Sparkles, Target } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api,json,Drive,DriveContext } from './api';
import { useAuth } from './auth';
import { ErrorMessage,PageHeading,useResource } from './ui';
import { download } from './career-profile';
type Topic={topic:string;why:string;outcome:string;priority:string};
type Plan={id:string;drive_id?:string;role_title:string;company_name:string;target_date:string;plan:{summary:string;goal:string;priority_topics:Topic[];daily_roadmap:{day:number;title:string;focus:string;activities:string[];success_check:string}[];discussion_starters:string[]};messages?:{id:string;role:string;content:string}[]};
type CoachRecommendation={available:boolean;drive_id?:string;role_title?:string;message:string;weak_skills:{focus?:string;problem?:string;actions?:string[]}[]};
export function Coach(){
 const {identity}=useAuth(),plans=useResource<{plans:Plan[]}>('/api/student/coach/plans'),drives=useResource<Drive[]>('/api/student/drives'),recommendation=useResource<CoachRecommendation>('/api/student/coach/latest-recommendation'),[params]=useSearchParams();
 const requestedDrive=params.get('drive')||'';
 const [selected,setSelected]=useState(''),[role,setRole]=useState(identity?.student.target_role||''),[company,setCompany]=useState(''),[jd,setJd]=useState(''),[date,setDate]=useState(''),[drive,setDrive]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function chooseDrive(id:string){setDrive(id);if(!id)return;setBusy(true);setError('');try{const context=await api<DriveContext>(`/api/student/drives/${id}/interview-context`);setRole(context.role_title);setJd(context.job_description);setCompany(context.company_name||drives.data?.find(d=>d.id===id)?.company_name||'');const target=(context.interview_window_start_at||'').slice(0,10);setDate(target>=new Date().toISOString().slice(0,10)?target:'');const existing=plans.data?.plans.find(p=>p.drive_id===id);if(existing)setSelected(existing.id)}catch(e){setDrive('');setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(requestedDrive&&drives.data&&!drive)void chooseDrive(requestedDrive)},[requestedDrive,drives.data]);
 return <><PageHeading eyebrow="YOUR PERSONAL TRAINING ROOM" title="AI Coach">Build a focused plan, talk naturally with your coach, and strengthen the areas that matter for your next attempt.</PageHeading>{error&&<ErrorMessage message={error}/>}
 <section className="coach-hero panel"><div className="coach-avatar" aria-hidden="true"><span><Bot size={46}/></span><i/><i/><i/></div><div><span className="eyebrow"><Sparkles size={14}/> VOICEDOT COACH</span><h2>Meet your role preparation coach</h2><p>Choose a placement opportunity and the coach will use its role, JD, and any released feedback from your completed attempt to build the next plan.</p><div className="coach-capabilities"><span><Mic size={16}/> Voice lessons</span><span><MessageCircle size={16}/> Saved discussion</span><span><Target size={16}/> Weak-area training</span></div></div></section>
 {recommendation.data?.available&&<section className="panel coach-recommendation"><div><span className="eyebrow">AFTER YOUR COMPLETED INTERVIEW</span><h2>Build your next practice session</h2><p>{recommendation.data.message}</p><div className="focus-chips">{recommendation.data.weak_skills.map((skill,i)=><span key={i}>{skill.focus||'Skill focus'}</span>)}</div></div>{recommendation.data.drive_id&&<button className="button primary" onClick={()=>void chooseDrive(recommendation.data!.drive_id!)}>Practice these skills</button>}</section>}
 <div className="coach-layout"><section className="panel coach-setup"><div className="section-heading"><div><span className="eyebrow">SET YOUR TARGET</span><h2>{drive?'Prepare for another attempt':'Create a preparation plan'}</h2></div><CalendarDays size={24}/></div><form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void api<Plan>('/api/student/coach/plans',{...json({role_title:role,company_name:company,job_description:jd,interview_date:date,drive_id:drive||null}),timeoutMs:180000}).then(p=>{plans.reload();setSelected(p.id)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}><fieldset disabled={busy}>
 <label>Placement opportunity<select value={drive} onChange={e=>void chooseDrive(e.target.value)}><option value="">Use my own job description</option>{drives.data?.map(d=><option key={d.id} value={d.id}>{d.company_name} — {d.role_title}</option>)}</select></label>
 <div className="career-grid"><label>Target role<input required minLength={2} maxLength={200} value={role} readOnly={!!drive} onChange={e=>setRole(e.target.value)}/></label><label>Company<input maxLength={200} value={company} readOnly={!!drive} onChange={e=>setCompany(e.target.value)}/></label><label>Interview date<input type="date" required min={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/><small>When do you want to be ready for your next attempt?</small></label></div><label>Job description<textarea required minLength={20} maxLength={20000} rows={5} value={jd} readOnly={!!drive} onChange={e=>setJd(e.target.value)}/></label><button className="button primary">{busy?'Building your coaching plan…':drive?'Build my next-attempt plan':'Create preparation plan'}</button></fieldset></form></section>
 <section className="panel coach-plan-picker"><span className="eyebrow">SAVED PLANS</span><h2>Your coaching rooms</h2>{plans.error&&<ErrorMessage message={plans.error} retry={plans.reload}/>}<div className="coach-plan-list">{plans.data?.plans.map(p=><button aria-label={`${p.role_title} · ${p.target_date?.slice(0,10)}`} aria-pressed={selected===p.id} className="coach-plan-button" key={p.id} onClick={()=>setSelected(p.id)}><span className="mini-coach"><Bot size={20}/></span><span><strong>{p.role_title}</strong><small>{p.company_name} · {p.target_date?.slice(0,10)}</small></span></button>)}</div>{!plans.loading&&!plans.data?.plans.length&&<p>Create a plan to open your first coaching room.</p>}</section></div>
 {selected&&<PlanDetail key={selected} id={selected} onDelete={()=>{setSelected('');plans.reload()}}/>}<p><Link to="/profile">Update your projects and tailor your resume</Link> · <Link to="/practice">Put your learning into interview practice</Link></p></>
}
function PlanDetail({id,onDelete}:{id:string;onDelete:()=>void}){
 const navigate=useNavigate();
 const resource=useResource<Plan>(`/api/student/coach/plans/${id}`),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const p=resource.data;
 async function send(text:string){if(!text.trim()||busy)return;setBusy(true);setError('');try{await api(`/api/student/coach/plans/${id}/messages`,{...json({message:text}),timeoutMs:180000});setMessage('');resource.reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="coach-room">{(error||resource.error)&&<ErrorMessage message={error||resource.error} retry={resource.reload}/>} {p&&<><header className="panel coach-room-header"><div className="mini-coach large"><Bot size={28}/></div><div><span className="eyebrow">ACTIVE COACHING PLAN</span><h2>{p.role_title}</h2><p>{p.company_name} · Target {p.target_date?.slice(0,10)}</p></div><div className="career-actions"><button className="button secondary" onClick={()=>void download(`/api/student/coach/plans/${id}/pdf`,'Preparation-plan.pdf').catch(e=>setError(e.message))}>Download plan</button><button className="text-button" disabled={busy} onClick={()=>{if(confirm('Delete this preparation plan and its conversation?')){setBusy(true);void api(`/api/student/coach/plans/${id}`,{method:'DELETE'}).then(onDelete).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}}>Delete</button></div></header>
 <section className="panel"><h3>{p.plan.goal}</h3><p>{p.plan.summary}</p><div className="coach-topic-grid">{p.plan.priority_topics.map((t,i)=><article className="coach-topic" key={i}><span className={`priority priority-${t.priority}`}>{t.priority}</span><h3>{t.topic}</h3><p>{t.why}</p><div><CheckCircle2 size={16}/><span>{t.outcome}</span></div></article>)}</div></section>
 <section className="panel"><div className="section-heading"><div><span className="eyebrow">STEP BY STEP</span><h3>Your roadmap</h3></div></div><div className="roadmap-timeline">{p.plan.daily_roadmap.map((d,i)=><details key={i}><summary><span>{d.day}</span><div><strong>Day {d.day}: {d.title}</strong><small>{d.focus}</small></div></summary><ul>{d.activities.map((a,j)=><li key={j}>{a}</li>)}</ul><p><CheckCircle2 size={15}/> {d.success_check}</p></details>)}</div></section>
 </>}
 <section className="coach-voice-launch"><div><span className="eyebrow">LIVE AI COACH</span><h3>Connect with Neha</h3><p>Open a private voice session for this role. Your completed discussion is saved here.</p></div><button className="button primary" onClick={()=>navigate(`/coach/session?plan=${encodeURIComponent(id)}`)}><Mic size={17}/> Connect AI Coach</button></section>
 <section className="panel coach-chat"><div className="section-heading"><div><span className="eyebrow">CONTINUE THE LESSON</span><h3>Chat with your coach</h3></div><MessageCircle size={23}/></div><div className="coach-messages" aria-label="Saved coach conversation">{p?.messages?.map((m,i)=><article key={m.id||i} className={`coach-message ${m.role==='student'?'student':''}`}><span className="message-avatar">{m.role==='student'?'You':<Bot size={17}/>}</span><div><strong>{m.role==='student'?'You':'AI Coach'}</strong><p>{m.content}</p></div></article>)}</div>
 <div className="coach-starters">{p?.plan.discussion_starters?.map((s,i)=><button className="text-button" disabled={busy} key={i} onClick={()=>void send(s)}>{s}</button>)}</div><form className="coach-compose" onSubmit={e=>{e.preventDefault();void send(message)}}><textarea aria-label="Ask your coach" required maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask for an explanation, example, or what to study next…"/><button className="button primary" disabled={busy||!p}>{busy?'Coach is thinking…':'Send message'}</button></form></section>
 </section>
}
