import { useEffect, useState } from 'react';
import { Bot, CalendarDays, CheckCircle2, MessageCircle, Mic, Sparkles, Target } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api,json,Drive,DriveContext } from './api';
import { useAuth } from './auth';
import { dateTime, ErrorMessage,PageHeading,useResource } from './ui';
import { download } from './career-profile';
type Topic={topic:string;why:string;outcome:string;priority:string};
type Plan={id:string;drive_id?:string;role_title:string;company_name:string;target_date:string;plan:{summary:string;goal:string;priority_topics:Topic[];daily_roadmap:{day:number;title:string;focus:string;activities:string[];success_check:string}[];discussion_starters:string[]};messages?:{id:string;role:string;content:string}[]};
type CoachCycle={id:string;plan_id:string;drive_id?:string;source_evaluation_id?:string;focus_skills:{focus?:string;problem?:string;actions?:string[]}[];call_scheduled_for:string;call_duration_minutes:number;call_started_at?:string;call_completed_at?:string;practice_status:string;interview_scheduled_for?:string;interview_duration_minutes?:number;interview_difficulty?:string;practice_url?:string};
type CoachRecommendation={available:boolean;evaluation_id?:string;drive_id?:string;plan_id?:string;role_title?:string;message:string;weak_skills:{focus?:string;problem?:string;actions?:string[]}[];cycle?:CoachCycle};
type CoachOverview={upcoming_drives:{drive_id:string;company_name:string;role_title:string;window_start_at?:string;window_end_at?:string;has_coaching_plan:boolean}[];completed_drive_recommendation?:CoachRecommendation};
export function Coach(){
 const {identity}=useAuth(),plans=useResource<{plans:Plan[]}>('/api/student/coach/plans'),drives=useResource<Drive[]>('/api/student/drives'),overview=useResource<CoachOverview>('/api/student/coach/overview'),recommendation=useResource<CoachRecommendation>('/api/student/coach/latest-recommendation'),cycles=useResource<{cycles:CoachCycle[]}>('/api/student/coach/training-cycles'),[params]=useSearchParams();
 const requestedDrive=params.get('drive')||'';
 const [selected,setSelected]=useState(''),[role,setRole]=useState(identity?.student.target_role||''),[company,setCompany]=useState(''),[jd,setJd]=useState(''),[date,setDate]=useState(''),[drive,setDrive]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function chooseDrive(id:string){setDrive(id);if(!id)return;setBusy(true);setError('');try{const context=await api<DriveContext>(`/api/student/drives/${id}/interview-context`);setRole(context.role_title);setJd(context.job_description);setCompany(context.company_name||drives.data?.find(d=>d.id===id)?.company_name||'');const target=(context.interview_window_start_at||'').slice(0,10);setDate(target>=new Date().toISOString().slice(0,10)?target:'');const existing=plans.data?.plans.find(p=>p.drive_id===id);if(existing)setSelected(existing.id)}catch(e){setDrive('');setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(!drives.data||drive)return;const next=requestedDrive||drives.data.find(item=>['scheduled','active'].includes(item.status))?.id;if(next)void chooseDrive(next)},[requestedDrive,drives.data]);
 useEffect(()=>{const recommendedPlan=recommendation.data?.plan_id;if(recommendedPlan&&plans.data?.plans.some(plan=>plan.id===recommendedPlan))setSelected(recommendedPlan)},[recommendation.data?.plan_id,plans.data]);
 useEffect(()=>{if(!selected&&plans.data?.plans.length&&!drive)setSelected(plans.data.plans[0].id)},[plans.data,selected,drive]);
 return <><PageHeading eyebrow="YOUR PERSONAL TRAINING ROOM" title="AI Coach">Build a focused plan, talk naturally with your coach, and strengthen the areas that matter for your next attempt.</PageHeading>{error&&<ErrorMessage message={error}/>}
 <section className="coach-hero panel"><div className="coach-avatar coach-avatar-photo" aria-hidden="true"><img src="/assets/panel/stills/neha-v3-idle.png" alt=""/><i/><i/><i/></div><div><span className="eyebrow"><Sparkles size={14}/> VOICEDOT COACH</span><h2>Meet your role preparation coach</h2><p>Choose a placement opportunity and the coach will use its role, JD, and any released feedback from your completed attempt to build the next plan.</p><div className="coach-capabilities"><span><Mic size={16}/> Voice lessons</span><span><MessageCircle size={16}/> Saved discussion</span><span><Target size={16}/> Weak-area training</span></div></div></section>
 <section className="panel coach-next-drives"><div className="section-heading"><div><span className="eyebrow">REAL PLACEMENT DATA</span><h2>Prepare for your next opportunity</h2><p>These are drives assigned to you. Select one to use its official role and job description.</p></div><CalendarDays size={24}/></div><div className="coach-drive-cards">{(overview.data?.upcoming_drives||[]).slice(0,4).map(item=><button key={item.drive_id} className={`coach-drive-card ${drive===item.drive_id?'selected':''}`} onClick={()=>void chooseDrive(item.drive_id)}><strong>{item.company_name}</strong><span>{item.role_title}</span><small>{item.window_start_at?dateTime(item.window_start_at):'Date to be confirmed'} · {item.has_coaching_plan?'Plan ready':'Build a plan'}</small></button>)}{!overview.loading&&!overview.data?.upcoming_drives?.length&&<p className="muted">No upcoming eligible placement drives are available yet.</p>}</div></section>
 {recommendation.data?.available&&<section className="panel coach-recommendation"><div><span className="eyebrow">YOUR NEXT IMPROVEMENT CYCLE</span><h2>Turn interview feedback into your next attempt</h2><p>{recommendation.data.message}</p><div className="focus-chips">{recommendation.data.weak_skills.map((skill,i)=><span key={i}>{skill.focus||'Skill focus'}</span>)}</div><div className="coach-cycle-preview"><span><b>1</b>Schedule a Coach call</span><span><b>2</b>Learn and practise weak skills</span><span><b>3</b>Take a focused practice interview</span></div></div>{recommendation.data.drive_id&&<button className="button primary" onClick={()=>void chooseDrive(recommendation.data!.drive_id!)}>Prepare these skills</button>}</section>}
 <div className="coach-layout"><section className="panel coach-setup"><div className="section-heading"><div><span className="eyebrow">SET YOUR TARGET</span><h2>{drive?'Prepare for another attempt':'Create a preparation plan'}</h2></div><CalendarDays size={24}/></div><form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void api<Plan>('/api/student/coach/plans',{...json({role_title:role,company_name:company,job_description:jd,interview_date:date,drive_id:drive||null}),timeoutMs:180000}).then(p=>{plans.reload();setSelected(p.id)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}><fieldset disabled={busy}>
 <label>Placement opportunity<select value={drive} onChange={e=>void chooseDrive(e.target.value)}><option value="">Use my own job description</option>{drives.data?.map(d=><option key={d.id} value={d.id}>{d.company_name} — {d.role_title}</option>)}</select></label>
 <div className="career-grid"><label>Target role<input required minLength={2} maxLength={200} value={role} readOnly={!!drive} onChange={e=>setRole(e.target.value)}/></label><label>Company<input maxLength={200} value={company} readOnly={!!drive} onChange={e=>setCompany(e.target.value)}/></label><label>Interview date<input type="date" required min={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/><small>When do you want to be ready for your next attempt?</small></label></div><label>Job description<textarea required minLength={20} maxLength={20000} rows={5} value={jd} readOnly={!!drive} onChange={e=>setJd(e.target.value)}/></label><button className="button primary">{busy?'Building your coaching plan…':drive?'Build my next-attempt plan':'Create preparation plan'}</button></fieldset></form></section>
 <section className="panel coach-plan-picker"><span className="eyebrow">SAVED PLANS</span><h2>Your coaching rooms</h2>{plans.error&&<ErrorMessage message={plans.error} retry={plans.reload}/>}<div className="coach-plan-list">{plans.data?.plans.map(p=><button aria-label={`${p.role_title} · ${p.target_date?.slice(0,10)}`} aria-pressed={selected===p.id} className="coach-plan-button" key={p.id} onClick={()=>setSelected(p.id)}><span className="mini-coach"><Bot size={20}/></span><span><strong>{p.role_title}</strong><small>{p.company_name} · {p.target_date?.slice(0,10)}</small></span></button>)}</div>{!plans.loading&&!plans.data?.plans.length&&<p>Create a plan to open your first coaching room.</p>}</section></div>
 {selected&&<PlanDetail key={selected} id={selected} recommendation={recommendation.data||undefined} cycle={cycles.data?.cycles.find(item=>item.plan_id===selected)||recommendation.data?.cycle} onCycle={()=>{cycles.reload();recommendation.reload()}} onDelete={()=>{setSelected('');plans.reload();cycles.reload()}}/>}<p><Link to="/profile">Update your projects and tailor your resume</Link> · <Link to="/practice">Put your learning into interview practice</Link></p></> 
}
function PlanDetail({id,recommendation,cycle,onCycle,onDelete}:{id:string;recommendation?:CoachRecommendation;cycle?:CoachCycle;onCycle:()=>void;onDelete:()=>void}){
 const navigate=useNavigate();
 const resource=useResource<Plan>(`/api/student/coach/plans/${id}`),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const p=resource.data;
 async function send(text:string){if(!text.trim()||busy)return;setBusy(true);setError('');try{await api(`/api/student/coach/plans/${id}/messages`,{...json({message:text}),timeoutMs:180000});setMessage('');resource.reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="coach-room">{(error||resource.error)&&<ErrorMessage message={error||resource.error} retry={resource.reload}/>} {p&&<><header className="panel coach-room-header"><div className="mini-coach large"><Bot size={28}/></div><div><span className="eyebrow">ACTIVE COACHING PLAN</span><h2>{p.role_title}</h2><p>{p.company_name} · Target {p.target_date?.slice(0,10)}</p></div><div className="career-actions"><button className="button secondary" onClick={()=>void download(`/api/student/coach/plans/${id}/pdf`,'Preparation-plan.pdf').catch(e=>setError(e.message))}>Download plan</button><button className="text-button" disabled={busy} onClick={()=>{if(confirm('Delete this preparation plan and its conversation?')){setBusy(true);void api(`/api/student/coach/plans/${id}`,{method:'DELETE'}).then(onDelete).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}}>Delete</button></div></header>
 <TrainingCycle planId={id} recommendation={recommendation} cycle={cycle} onChange={onCycle} onError={setError}/>
 <section className="panel"><h3>{p.plan.goal}</h3><p>{p.plan.summary}</p><div className="coach-topic-grid">{p.plan.priority_topics.map((t,i)=><article className="coach-topic" key={i}><span className={`priority priority-${t.priority}`}>{t.priority}</span><h3>{t.topic}</h3><p>{t.why}</p><div><CheckCircle2 size={16}/><span>{t.outcome}</span></div></article>)}</div></section>
 <section className="panel"><div className="section-heading"><div><span className="eyebrow">STEP BY STEP</span><h3>Your roadmap</h3></div></div><div className="roadmap-timeline">{p.plan.daily_roadmap.map((d,i)=><details key={i}><summary><span>{d.day}</span><div><strong>Day {d.day}: {d.title}</strong><small>{d.focus}</small></div></summary><ul>{d.activities.map((a,j)=><li key={j}>{a}</li>)}</ul><p><CheckCircle2 size={15}/> {d.success_check}</p></details>)}</div></section>
 </>}
 <section className="coach-voice-launch"><div><span className="eyebrow">LIVE AI COACH</span><h3>Connect with Neha</h3><p>{cycle?'Use your scheduled teaching room. Your completed discussion is saved here.':'Start a live practice conversation using this coaching plan.'}</p></div><button className="button primary" onClick={()=>navigate(`/coach/session?plan=${encodeURIComponent(id)}`)}><Mic size={17}/> Connect AI Coach</button></section>
 <section className="panel coach-chat"><div className="section-heading"><div><span className="eyebrow">CONTINUE THE LESSON</span><h3>Chat with your coach</h3></div><MessageCircle size={23}/></div><div className="coach-messages" aria-label="Saved coach conversation">{p?.messages?.map((m,i)=><article key={m.id||i} className={`coach-message ${m.role==='student'?'student':''}`}><span className="message-avatar">{m.role==='student'?'You':<Bot size={17}/>}</span><div><strong>{m.role==='student'?'You':'AI Coach'}</strong><p>{m.content}</p></div></article>)}</div>
 <div className="coach-starters">{p?.plan.discussion_starters?.map((s,i)=><button className="text-button" disabled={busy} key={i} onClick={()=>void send(s)}>{s}</button>)}</div><form className="coach-compose" onSubmit={e=>{e.preventDefault();void send(message)}}><textarea aria-label="Ask your coach" required maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask for an explanation, example, or what to study next…"/><button className="button primary" disabled={busy||!p}>{busy?'Coach is thinking…':'Send message'}</button></form></section>
 </section>
}

function localDateTime(hours=1){const value=new Date(Date.now()+hours*3600000);value.setMinutes(value.getMinutes()-value.getTimezoneOffset());return value.toISOString().slice(0,16)}
function TrainingCycle({planId,recommendation,cycle,onChange,onError}:{planId:string;recommendation?:CoachRecommendation;cycle?:CoachCycle;onChange:()=>void;onError:(value:string)=>void}){
 const [callAt,setCallAt]=useState(localDateTime()),[callMinutes,setCallMinutes]=useState('10'),[interviewAt,setInterviewAt]=useState(localDateTime(25)),[interviewMinutes,setInterviewMinutes]=useState('30'),[difficulty,setDifficulty]=useState('intermediate'),[busy,setBusy]=useState(false);
 async function scheduleCall(){setBusy(true);onError('');try{await api('/api/student/coach/training-cycles',{...json({plan_id:planId,source_evaluation_id:recommendation?.evaluation_id||null,scheduled_for:new Date(callAt).toISOString(),duration_minutes:Number(callMinutes)})});onChange()}catch(e){onError((e as Error).message)}finally{setBusy(false)}}
 async function scheduleInterview(){if(!cycle)return;setBusy(true);onError('');try{await api(`/api/student/coach/training-cycles/${encodeURIComponent(cycle.id)}/interview`,{...json({scheduled_for:new Date(interviewAt).toISOString(),duration_minutes:Number(interviewMinutes),difficulty})});onChange()}catch(e){onError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel coach-cycle"><div className="section-heading"><div><span className="eyebrow">COACHING CYCLE</span><h3>Learn, practise, then interview again</h3></div><span className="pill">{cycle?.practice_status||'Plan ready'}</span></div><div className="coach-cycle-steps"><article className={cycle?'complete':'active'}><b>1</b><div><strong>Schedule coaching call</strong>{cycle?<p>{dateTime(cycle.call_scheduled_for)} · {cycle.call_duration_minutes} minutes</p>:<div className="coach-schedule-fields"><label>Call time<input type="datetime-local" min={localDateTime(0)} value={callAt} onChange={e=>setCallAt(e.target.value)}/></label><label>Length<select value={callMinutes} onChange={e=>setCallMinutes(e.target.value)}><option value="10">10 minutes</option><option value="20">20 minutes</option></select></label><button className="button primary small" disabled={busy||!callAt} onClick={()=>void scheduleCall()}>Schedule call</button></div>}</div></article><article className={cycle?.call_completed_at?'complete':cycle?'active':''}><b>2</b><div><strong>Teaching and guided practice</strong><p>{cycle?.call_completed_at?'Coach call completed. Your focused practice interview is unlocked.':cycle?'Start the Coach call when you are ready.':'Complete step 1 to open your teaching room.'}</p></div></article><article className={cycle?.practice_status==='scheduled'||cycle?.practice_status==='started'?'complete':cycle?.call_completed_at?'active':''}><b>3</b><div><strong>Focused AI interview</strong>{cycle?.interview_scheduled_for?<><p>{dateTime(cycle.interview_scheduled_for)} · {cycle.interview_duration_minutes} minutes · {cycle.interview_difficulty}</p><Link className="button primary small" to={`/practice?coach_cycle=${encodeURIComponent(cycle.id)}`}>Start practice interview</Link></>:cycle?.call_completed_at?<div className="coach-schedule-fields"><label>Interview time<input type="datetime-local" min={localDateTime(0)} value={interviewAt} onChange={e=>setInterviewAt(e.target.value)}/></label><label>Length<select value={interviewMinutes} onChange={e=>setInterviewMinutes(e.target.value)}><option value="30">30 minutes</option><option value="45">45 minutes</option></select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><button className="button primary small" disabled={busy||!interviewAt} onClick={()=>void scheduleInterview()}>Schedule interview</button></div>:<p>Complete the teaching call to unlock this step.</p>}</div></article></div></section>
}
