import { useEffect, useState, type CSSProperties } from "react";
import { Link, useParams } from "react-router-dom";
import { Download, ArrowLeft, ArrowRight, CheckCircle2, MessageSquare, Mic, Play, RefreshCw } from "lucide-react";
import { api, apiUrl, request, type Report, type QuestionReview, type InterviewReportView, type AnswerCoaching } from "./api";
import { ErrorMessage, humanize, useResource, ResourceState, date, score } from "./ui";
import { PlacementResult } from "./report-result";

type Recording = { status: string; playback_url: string | null; message?: string };
const evidenceLabels: Record<string,string> = { answered:"Response captured", limited_answer:"Limited evidence", explicit_dont_know:"Unsure", irrelevant_answer:"Off topic", capture_unavailable:"Capture unavailable", system_interrupted:"Interrupted", no_response:"No response", unanswered:"No response" };
const evidenceNotes: Record<string,string> = {
  answered:"Your response was captured and included in the assessment. No separate feedback was saved for this question.",
  limited_answer:"There was limited detail in this response. Add a concrete example, explain your approach, and describe the outcome.",
  explicit_dont_know:"You indicated that you were unsure. Review this topic, then practise explaining it with an example.",
  irrelevant_answer:"The saved response did not address the question. Start with a direct answer before adding supporting detail.",
  capture_unavailable:"The answer could not be captured. This is a recording issue, not a judgment of your ability.",
  system_interrupted:"The system interrupted this answer. The incomplete response does not provide enough evidence to assess it.",
  no_response:"No response was recorded for this question.", unanswered:"No response was recorded for this question.",
};
function AnswerAudio({sessionId, turnId}: {sessionId:string;turnId:string}) {
  const [url,setUrl]=useState(""), [busy,setBusy]=useState(false), [error,setError]=useState("");
  useEffect(() => () => { if(url) URL.revokeObjectURL(url); }, [url]);
  async function load() {
    setBusy(true);setError("");
    try { const response=await request(`/api/interview/${encodeURIComponent(sessionId)}/turns/${encodeURIComponent(turnId)}/audio`);setUrl(URL.createObjectURL(await response.blob())); }
    catch(cause) {setError(cause instanceof Error ? cause.message : "Unable to load answer audio.");}
    finally {setBusy(false);}
  }
  return <div className="report-answer-audio">{url ? <audio controls preload="metadata" src={url} aria-label="Your recorded answer"/> : <button className="button secondary small" disabled={busy} onClick={() => void load()}><Play size={14}/>{busy ? "Loading audio…" : error ? "Retry answer audio" : "Listen to your answer"}</button>}{error && <p role="status">{error}</p>}</div>;
}
function QuestionCard({question,index,sessionId,view,coaching,busy}: {question:QuestionReview;index:number;sessionId:string;view:InterviewReportView;coaching?:AnswerCoaching;busy?:boolean}) {
  const positive=question.strength_feedback || view.strengths?.filter(item => item.cites_answer_id === question.answer_id).map(item => item.text || "") || [];
  const improve=question.improvement_feedback || view.improvements?.filter(item => typeof item !== "string" && item.cites_answer_id === question.answer_id).map(item => typeof item === "string" ? item : item.text || "") || [];
  return <details className="report-question" open={index===0}>
    <summary><span className="report-question-number">{String(index+1).padStart(2,"0")}</span><span className="report-question-heading"><span>{humanize(question.round || "Interview")}{question.kind === "followup" ? " · Follow-up" : ""}</span><strong>{question.question || "Interview question"}</strong></span><span className="report-evidence-label">{evidenceLabels[question.evidence_status || ""] || "Response recorded"}</span></summary>
    <div className="report-question-content"><div className="report-response"><span className="report-section-label">YOUR RESPONSE</span><p>{question.answer || "No answer transcript is available."}</p>{question.has_audio && question.turn_id && <AnswerAudio sessionId={sessionId} turnId={question.turn_id}/>}</div>
      <div className="report-question-feedback"><span className="report-section-label">QUESTION FEEDBACK</span>{coaching ? <><div className="report-feedback-positive"><span>What worked</span><p>{coaching.what_worked}</p></div><div className="report-feedback-next"><span>Try next time</span><p>{coaching.improve}</p></div><p className="report-feedback-evidence">From your answer: “{coaching.evidence_quote}”</p></> : <>{positive.filter(Boolean).map((text,i) => <div className="report-feedback-positive" key={`s-${i}`}><span>What worked</span><p>{text}</p></div>)}{improve.filter(Boolean).map((text,i) => <div className="report-feedback-next" key={`i-${i}`}><span>Try next time</span><p>{text}</p></div>)}{!positive.filter(Boolean).length && !improve.filter(Boolean).length && <p>{busy ? "Preparing feedback from your saved answer…" : evidenceNotes[question.evidence_status || ""] || "No separate feedback was saved for this response."}</p>}</>}</div></div>
  </details>;
}
export function InterviewReport() {
  const {sessionId=""}=useParams();
  const reports=useResource<{reports:Report[]}>("/api/student/reports");
  const report=reports.data?.reports.find(item => item.session_id===sessionId);
  const released=report?.status === "released" && report.report?.status !== "awaiting_release";
  const detail=useResource<InterviewReportView>(released ? `/api/interview/${encodeURIComponent(sessionId)}/evaluation` : null);
  const recording=useResource<Recording>(released ? `/api/student/interview/${encodeURIComponent(sessionId)}/recording` : null);
  const [tab,setTab]=useState<"overview"|"questions"|"recording">("overview");
  const [feedback,setFeedback]=useState<Record<string,AnswerCoaching>>({});
  const [feedbackBusy,setFeedbackBusy]=useState(false),[feedbackError,setFeedbackError]=useState(""),[feedbackLoaded,setFeedbackLoaded]=useState(false);
  const [mediaError,setMediaError]=useState("");
  useEffect(() => {setTab("overview");setMediaError("");setFeedback({});setFeedbackLoaded(false);setFeedbackError("");},[sessionId]);
  useEffect(() => {
    if(tab!=="questions" || !detail.data || feedbackLoaded) return;
    const controller=new AbortController();setFeedbackBusy(true);setFeedbackError("");
    void api<{feedback:Record<string,AnswerCoaching>;complete:boolean}>(`/api/interview/${encodeURIComponent(sessionId)}/evaluation/question-feedback`,{method:"POST",signal:controller.signal,timeoutMs:180000}).then(result=>{if(!controller.signal.aborted){setFeedback(result.feedback);if(!result.complete)setFeedbackError("Some answer feedback is still unavailable. Retry to complete it.");}}).catch(cause=>{if(!controller.signal.aborted)setFeedbackError(cause.message);}).finally(()=>{if(!controller.signal.aborted){setFeedbackBusy(false);setFeedbackLoaded(true);}});
    return ()=>controller.abort();
  },[tab,detail.data,sessionId,feedbackLoaded]);
  const view=detail.data;
  const answerFeedback={...(view?.question_feedback || {}),...feedback};
  const questions=view?.question_reviews || [];
  const dimensions=Object.entries(view?.score_breakdown || {});
  const points=view?.overall_score;
  return <section className="interview-report-page report-workspace">
    <Link className="report-back-link" to="/reports"><ArrowLeft size={16}/> All reports</Link>
    <ResourceState resource={reports}>{report ? <>
      <header className="full-report-header"><div><span className="eyebrow">{report.drive_id ? "PLACEMENT INTERVIEW" : "PRACTICE INTERVIEW"}</span><h1>{report.target_role || "Your interview"}</h1><p>{report.company_name || "Self practice"} · {date(report.completed_at || report.created_at)}{report.attempt_number ? ` · Attempt ${report.attempt_number}` : ""}</p></div>{released && <a className="button secondary" href={apiUrl(`/api/interview/${encodeURIComponent(sessionId)}/evaluation/report.pdf`)}><Download size={16}/> Download PDF</a>}</header>
      {!released ? <section className="panel report-awaiting"><MessageSquare size={24}/><h2>Your feedback is being prepared</h2><p>Your report and placement result will appear here when they are released.</p></section> : <ResourceState resource={detail}>{view && <>
        {report.drive_id && <PlacementResult value={report.placement_decision}/>}
        <nav className="report-section-nav" aria-label="Report sections">{([{key:"overview",label:"Overview",Icon:CheckCircle2},{key:"questions",label:`Questions & feedback (${questions.length})`,Icon:MessageSquare},{key:"recording",label:"Recording & audio",Icon:Mic}] as const).map(({key,label,Icon}) => <button key={key} aria-pressed={tab===key} onClick={() => setTab(key)}><Icon size={16}/>{label}</button>)}</nav>
        {tab === "overview" && <div className="report-overview-content"><section className="report-performance panel"><div className="report-score-block"><div className={`report-score-ring ${points == null ? "is-unscored" : ""}`} style={{"--report-score":`${Math.max(0,Math.min(100,points ?? 0))}%`} as CSSProperties}><div><strong>{points == null ? "—" : score(points)}</strong><span>Interview score</span></div></div><div><span className="report-section-label">YOUR PERFORMANCE</span><h2>{points == null ? "Assessment pending" : humanize(view.readiness || "Feedback ready")}</h2><p>Your interview performance is separate from your placement decision.</p>{view.assessment_coverage_percent != null && <span className="report-coverage">{view.assessment_coverage_percent}% assessment coverage</span>}</div></div><div className="report-score-breakdown"><h3>Skills in focus</h3>{dimensions.length ? dimensions.map(([label,value]) => <div className="report-score-row" key={label}><span>{humanize(label)}</span><progress max={100} value={value ?? 0} aria-label={label}/><span>{value == null ? "Not assessed" : score(value)}</span></div>) : <p>A skill breakdown is not available for this interview.</p>}</div></section>
          <div className="report-guidance-grid"><div className="report-guidance-stack"><section className="panel report-guidance"><span className="eyebrow">BUILD ON THIS</span><h2>What went well</h2>{view.strengths?.length ? view.strengths.map((item,index) => <div className="report-strength" key={index}><CheckCircle2 size={17}/><p>{item.text || item.focus}</p></div>) : <p>No specific strengths were saved in this report.</p>}</section>{view.communication && <section className="panel report-guidance"><span className="eyebrow">HOW YOU COMMUNICATED</span><h2>Your speaking snapshot</h2><div className="report-speaking-metrics">{view.communication.speaking_speed_wpm != null && <div><strong>{view.communication.speaking_speed_wpm}</strong><span>Words per minute</span></div>}{view.communication.filler_word_count != null && <div><strong>{view.communication.filler_word_count}</strong><span>Filler words</span></div>}</div>{view.communication.measurement_note && <p>{view.communication.measurement_note}</p>}{view.communication.top_filler_words?.length ? <div className="report-filler-chips">{view.communication.top_filler_words.map(word=><span key={word}>{word}</span>)}</div> : null}{view.communication.scores && <div className="report-speaking-scores">{Object.entries(view.communication.scores).map(([label,value])=><div key={label}><span>{humanize(label)}</span><span>{value == null ? "Not assessed" : score(value)}</span></div>)}</div>}</section>}</div><section className="panel report-guidance"><span className="eyebrow">YOUR NEXT PRACTICE</span><h2>Where to focus</h2>{view.priority_improvement_areas?.length ? view.priority_improvement_areas.map((item,index) => <article className="report-improvement" key={index}><span className="report-question-number">{String(index+1).padStart(2,"0")}</span><div><h3>{item.focus || "Practice focus"}</h3>{item.problem && <p>{item.problem}</p>}{item.actions?.length ? <ul>{item.actions.map((action,i) => <li key={i}>{action}</li>)}</ul> : null}</div></article>) : view.improvements?.length ? view.improvements.map((item,index) => <p key={index}>{typeof item === "string" ? item : item.text || item.focus}</p>) : <p>No practice priorities were saved in this report.</p>}<Link className="button secondary small" to={report.drive_id ? `/coach?drive=${encodeURIComponent(report.drive_id)}` : "/practice"}>{report.drive_id ? "Prepare with AI Coach" : "Practise another interview"}<ArrowRight size={15}/></Link></section></div>
          <button className="report-question-cta" onClick={() => setTab("questions")}><MessageSquare size={20}/><span><strong>Review every answer</strong><span>Read your responses and the feedback linked to each question.</span></span><ArrowRight size={18}/></button>
        </div>}
        {tab === "questions" && <section className="report-questions-section"><div className="report-section-heading"><div><h2>Questions & feedback</h2><p>Your saved responses, including follow-ups, with feedback from this interview.</p></div><span>{questions.length} {questions.length === 1 ? "response" : "responses"}</span></div>{feedbackBusy && <p className="report-feedback-loading" role="status">Preparing answer-specific feedback. Your responses are ready to read below.</p>}{feedbackError && <ErrorMessage message={feedbackError} retry={() => setFeedbackLoaded(false)}/>} {questions.length ? questions.map((question,index) => <QuestionCard key={`${question.answer_id ?? index}-${question.turn_id || ""}`} question={question} index={index} sessionId={sessionId} view={view} coaching={answerFeedback[String(question.answer_id)]} busy={feedbackBusy}/>) : <div className="panel"><p>Question-level responses are not available for this earlier interview.</p></div>}</section>}
        {tab === "recording" && <section className="panel report-recording-section"><span className="eyebrow">LISTEN & REFLECT</span><h2>Interview recording</h2><p>Replay your interview or listen to an individual answer.</p>{recording.loading ? <p role="status">Checking recording availability…</p> : recording.error ? <ErrorMessage message={recording.error} retry={recording.reload}/> : recording.data?.playback_url ? <div className="report-media"><video className="report-video" controls playsInline preload="metadata" src={recording.data.playback_url} aria-label="Interview video" onError={() => setMediaError("The recording could not be played. Refresh its link and try again.")}/><h3>Audio only</h3><audio controls preload="none" src={recording.data.playback_url} aria-label="Full interview audio" onError={() => setMediaError("Audio playback is unavailable in this browser. Try the video or an individual answer.")}/>{mediaError && <p role="status">{mediaError}</p>}<button className="button secondary small" onClick={() => {setMediaError("");recording.reload();}}><RefreshCw size={14}/>Refresh recording</button></div> : <p className="report-media-unavailable">{recording.data?.message || (recording.data?.status === "processing" ? "Your interview recording is still processing. Check back shortly." : "No full interview recording was saved for this session.")}</p>}
          <div className="report-audio-list">{questions.filter(question => question.has_audio && question.turn_id).map((question,index) => <article key={question.turn_id}><span className="report-question-number">{String(index+1).padStart(2,"0")}</span><div><h3>{question.question || "Recorded answer"}</h3><AnswerAudio sessionId={sessionId} turnId={question.turn_id!}/></div></article>)}</div>{!questions.some(question => question.has_audio) && <p className="report-audio-note">Separate answer audio is not available for this interview. Your saved responses are in Questions & feedback.</p>}</section>}
      </>}</ResourceState>}
    </> : reports.data && <p className="panel">This report is unavailable.</p>}</ResourceState>
  </section>;
}
